Added shroud that crashes when you select front 6 layers. Due to panicked at library\core\src\slice\sort\shared\smallsort.rs:860:5: user-provided comparison function does not correctly implement a total order